# Generated by Django 5.2 on 2025-05-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_correspondence', models.DateField(blank=True, null=True)),
                ('corresponder', models.CharField(blank=True, max_length=30)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers_.customer')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
