# Generated by Django 5.2 on 2025-04-14 19:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', unique=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2)),
                ('sales_owner', models.CharField(max_length=30)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(blank=True, choices=[('lead', 'Lead'), ('rejected', 'Rejected Lead'), ('customer', 'Customer'), ('lost', 'Lost Customer')], max_length=10)),
                ('loss_reason', models.TextField(blank=True)),
                ('cust_branch', models.CharField(blank=True, max_length=20)),
                ('branches', models.JSONField(blank=True, null=True)),
                ('market_cap', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
