# Generated by Django 5.2 on 2025-04-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_branch',
            new_name='contact_branch',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_designation',
            field=models.CharField(default='CEO', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
