# Generated by Django 5.2 on 2025-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch_address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lifecycle_status',
            field=models.CharField(blank=True, choices=[('lead', 'Lead'), ('rejected', 'Rejected Lead'), ('customer', 'Customer'), ('lost', 'Lost Customer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loss_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
