# Generated by Django 5.2 on 2025-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_', '0002_rename_cust_branch_customer_contact_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='branches',
            new_name='company_branches',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='branch_address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='contacted_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
